# Generated by Django 3.1.1 on 2020-11-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conv'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conv',
            name='conv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
